build:
   stage: build
   only:
    - Dev
   script:
      - make DungeonGame
   artifacts:

         
test:
   stage: test
   script:
      - DungeonGame


pages:
   stage: deploy
   dependencies:
      - test
   script:
      - make memory
      - make coverage
      - make static
      - make style
      - make docs
   artifacts:
      paths:
         - coverage
         - docs
      expire_in: 14 days
